### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by day7500** [healingbrew/HFSExtract#1]
I want to extract HFS files from a "Vindictus" Korean server.
When you compile and use the source, only "unknown.bin" is generated continuously.

I want to extract each information file and organize the game strategy and information in the Korean community.
If you help, I will use it in a useful place. Thank you.

**Comment by Yentis** [comment]
Using the release version:
- Open cmd
- Navigate to the exe folder

Type the following:
`HFSExtract.CLI.exe hfs_directory extract_directory [summary.txt]`

Where hfs_directory is the location of the hfs files, extract_directory is where you want the extracted files to go and summary.txt is an optional log file.
