### ISSUE TITLE
Is my usage wrong?

### ISSUE THREAD

**Issue by lcfkbs** [healingbrew/HFSExtract#5]
![image](https://user-images.githubusercontent.com/67427525/132955885-f673cdaf-d0df-43f6-88b4-fa688a6c14a0.png)

**Comment by lcfkbs** [comment]
Sorry, I'm a rookie. I want to know what's wrong with me

**Comment by andrewdesi** [comment]
Getting the same error.

**Comment by CrossV4** [comment]
did you figure it out ?

**Comment by ValiaP** [comment]
Getting the same error.

**Comment by ValiaP** [comment]
Open cmd with administrator mode seems to solve this.
